addSbtPlugin("com.codecommit"    % "sbt-github-actions"  % "0.10.1")
addSbtPlugin("org.scalameta"     % "sbt-mdoc"            % "2.2.21")
addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"          % "0.4.3")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "1.0.0")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.9.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-site"            % "1.4.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.8.1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.8.2")
addSbtPlugin("com.simplytyped"   % "sbt-antlr4"          % "0.8.2")
// addSbtPlugin("ch.epfl.lamp"      % "sbt-dotty"           % "0.4.2")
addSbtPlugin("org.lyranthe.sbt"  % "partial-unification" % "1.1.2")
addCompilerPlugin("com.olegpy"   %% "better-monadic-for" % "0.3.1")
addSbtPlugin("com.geirsson"      % "sbt-ci-release"      % "1.5.7")
